# Generated by Django 2.2.4 on 2021-10-27 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_mesa', models.CharField(max_length=5, verbose_name='Mesa')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'ordering': ['nro_mesa'],
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Titulo')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('ingredientes', models.TextField(verbose_name='Ingredientes')),
                ('instrucciones', models.TextField(verbose_name='Instrucciones')),
                ('imagen', models.ImageField(max_length=200, upload_to='receta/', verbose_name='Imagen Receta')),
                ('precio', models.PositiveIntegerField(default=0, verbose_name='Precio')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('insumo', models.CharField(max_length=255, verbose_name='Nombre insumo')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='cantidad insumo')),
                ('fecha_solicitud', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Solicitud')),
                ('estado', models.BooleanField(default=True, verbose_name='estado')),
                ('nombre_solicitante', models.CharField(max_length=255, verbose_name='nombre_solicitante')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Inicio')),
                ('fecha_cierre', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Cierre')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='notas')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantApp.Mesa')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=255, verbose_name='Nombre producto')),
                ('stock', models.PositiveIntegerField(default=1, verbose_name='Cantidad o Stock')),
                ('fecha_ult_revision', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha ultima revision')),
                ('disponibilidad_stock', models.BooleanField(default=True, verbose_name='Hay stock')),
                ('nombre_encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'ordering': ['producto'],
            },
        ),
    ]
